image: ubuntu:24.04

stages:
  - build
  - release

variables:
  MESON_BUILD_DIR: "_build"
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"
  UBUNTU_DEPS:
    appstream-util
    desktop-file-utils
    build-essential
    meson
    flex
    yelp-tools
    libexiv2-dev
    libgsf-1-dev
    libgtk-3-dev
    libpoppler-glib-dev
    libsmbclient-dev
    libtag1-dev
    libunique-dev
    libgtest-dev
    xvfb

include:
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: release
      dist-job-name: "tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -y $UBUNTU_DEPS

build:
  stage: build
  script:
    - mkdir ${MESON_BUILD_DIR}
    - meson setup ${MESON_BUILD_DIR}
    - meson compile -C ${MESON_BUILD_DIR}
    - exit_code=0
    - xvfb-run meson test -C ${MESON_BUILD_DIR} || exit_code=$?; if [ "$exit_code" != "0" ]; then echo "Unit tests failed."; cat ${MESON_BUILD_DIR}/meson-logs/testlog.txt; exit 1; fi;

tarball:
  stage: release
  script:
    - mkdir ${MESON_BUILD_DIR}
    - meson setup ${MESON_BUILD_DIR}
    - meson compile -C ${MESON_BUILD_DIR}
    - meson dist -C ${MESON_BUILD_DIR}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: "always"
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
  rules:
    - if: $CI_COMMIT_TAG
