/*
 * You may edit this file eventhough it was generated by Glade.
 */

GtkWidget* create_main_win (CvsPlugin *plugin);
GtkWidget* create_diff_dialog (CvsPlugin *plugin);
GtkWidget* create_about_dialog (void);
