/*
 * You may edit this file eventhough it was generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include <libgcmd/libgcmd.h>
#include "cvs-plugin.h"
#include "callbacks.h"
#include "interface.h"

static GnomeUIInfo file_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PRINT_ITEM (on_print, NULL),
  GNOMEUIINFO_MENU_PRINT_SETUP_ITEM (on_print_setup, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo cvs_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Compare Revisions..."),
    NULL,
    (gpointer) on_compare_revisions, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file_menu_uiinfo),
  {
    GNOME_APP_UI_SUBTREE, N_("CVS"),
    NULL,
    cvs_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_main_win (CvsPlugin *plugin)
{
  GtkWidget *main_win;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkWidget *hpaned1;
  GtkWidget *frame2;
  GtkWidget *scrolledwindow1;
  GtkWidget *rev_list;
  GtkWidget *label4;
  GtkWidget *frame1;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *label5;
  GtkWidget *rev_label;
  GtkWidget *label9;
  GtkWidget *author_label;
  GtkWidget *label7;
  GtkWidget *date_label;
  GtkWidget *label11;
  GtkWidget *state_label;
  GtkWidget *label13;
  GtkWidget *lines_label;
  GtkWidget *hseparator1;
  GtkWidget *label3;
  GtkWidget *scrolledwindow2;
  GtkWidget *msg_text;

  main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_win), "main_win", main_win);
  gtk_window_set_title (GTK_WINDOW (main_win), _("CVSLogViewer"));
  gtk_window_set_default_size (GTK_WINDOW (main_win), 510, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_win), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "file",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "print",
                            file_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "print_setup",
                            file_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "separator1",
                            file_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "exit",
                            file_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "cvs",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (cvs_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "compare_revisions",
                            cvs_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "help1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 100);

  frame2 = gtk_frame_new (_("Revisions"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), frame2, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 3);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame2), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  rev_list = gtk_clist_new (1);
  gtk_widget_ref (rev_list);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "rev_list", rev_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), rev_list);
  gtk_container_set_border_width (GTK_CONTAINER (rev_list), 3);
  gtk_clist_set_column_width (GTK_CLIST (rev_list), 0, 67);
  gtk_clist_column_titles_hide (GTK_CLIST (rev_list));

  label4 = gtk_label_new (_("revision"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_clist_set_column_widget (GTK_CLIST (rev_list), 0, label4);

  frame1 = gtk_frame_new (_("Information"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), frame1, TRUE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame1), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 6);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 12);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 6);

  label5 = gtk_label_new (_("Revision:"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  rev_label = gtk_label_new (_("..."));
  gtk_widget_ref (rev_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "rev_label", rev_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev_label);
  gtk_table_attach (GTK_TABLE (table1), rev_label, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (rev_label), 0, 0.5);

  label9 = gtk_label_new (_("Author:"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  author_label = gtk_label_new (_("..."));
  gtk_widget_ref (author_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "author_label", author_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (author_label);
  gtk_table_attach (GTK_TABLE (table1), author_label, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (author_label), 0, 0.5);

  label7 = gtk_label_new (_("Date:"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  date_label = gtk_label_new (_("..."));
  gtk_widget_ref (date_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "date_label", date_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_label);
  gtk_table_attach (GTK_TABLE (table1), date_label, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (date_label), 0, 0.5);

  label11 = gtk_label_new (_("State:"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  state_label = gtk_label_new (_("..."));
  gtk_widget_ref (state_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "state_label", state_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (state_label);
  gtk_table_attach (GTK_TABLE (table1), state_label, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (state_label), 0, 0.5);

  label13 = gtk_label_new (_("Lines:"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  lines_label = gtk_label_new (_("..."));
  gtk_widget_ref (lines_label);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "lines_label", lines_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lines_label);
  gtk_table_attach (GTK_TABLE (table1), lines_label, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lines_label), 0, 0.5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, FALSE, TRUE, 6);

  label3 = gtk_label_new (_("Message:"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox2), label3, FALSE, FALSE, 3);
  gtk_misc_set_alignment (GTK_MISC (label3), 7.45058e-09, 0.5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  msg_text = gtk_text_view_new ();
  gtk_widget_ref (msg_text);
  gtk_object_set_data_full (GTK_OBJECT (main_win), "msg_text", msg_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msg_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), msg_text);

  gtk_signal_connect (GTK_OBJECT (main_win), "show",
                      GTK_SIGNAL_FUNC (on_main_win_show),
                      plugin);
  gtk_signal_connect (GTK_OBJECT (rev_list), "select_row",
                      GTK_SIGNAL_FUNC (on_rev_list_select_row),
                      plugin);

  return main_win;
}

GtkWidget*
create_diff_dialog (CvsPlugin *plugin)
{
  GtkWidget *diff_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox3;
  GtkWidget *table2;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *rev1_combo;
  GtkWidget *rev1_entry;
  GtkWidget *rev2_combo;
  GtkWidget *rev2_entry;
  GtkWidget *diff_button;
  GtkWidget *frame3;
  GtkWidget *vbox4;
  GtkWidget *diff_text;
  GtkWidget *font_check;
  GtkWidget *dialog_action_area1;
  GtkWidget *close_button;

  diff_dialog = gnome_dialog_new (_("Compare revisions"), NULL);
  gtk_object_set_data (GTK_OBJECT (diff_dialog), "diff_dialog", diff_dialog);
  GTK_WINDOW (diff_dialog)->type = GTK_WINDOW_TOPLEVEL;
  gtk_window_set_default_size (GTK_WINDOW (diff_dialog), 400, 300);
  gtk_window_set_policy (GTK_WINDOW (diff_dialog), TRUE, TRUE, FALSE);

  dialog_vbox1 = GNOME_DIALOG (diff_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (diff_dialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox3 = gtk_vbox_new (FALSE, 12);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox3, TRUE, TRUE, 0);

  table2 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox3), table2, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 12);

  label14 = gtk_label_new (_("Revision 1:"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Revision 2:"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  rev1_combo = gtk_combo_new ();
  gtk_widget_ref (rev1_combo);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "rev1_combo", rev1_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev1_combo);
  gtk_table_attach (GTK_TABLE (table2), rev1_combo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  rev1_entry = GTK_COMBO (rev1_combo)->entry;
  gtk_widget_ref (rev1_entry);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "rev1_entry", rev1_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev1_entry);

  rev2_combo = gtk_combo_new ();
  gtk_widget_ref (rev2_combo);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "rev2_combo", rev2_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev2_combo);
  gtk_table_attach (GTK_TABLE (table2), rev2_combo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  rev2_entry = GTK_COMBO (rev2_combo)->entry;
  gtk_widget_ref (rev2_entry);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "rev2_entry", rev2_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rev2_entry);

  diff_button = gtk_button_new_with_label (_("Compare"));
  gtk_widget_ref (diff_button);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "diff_button", diff_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (diff_button);
  gtk_table_attach (GTK_TABLE (table2), diff_button, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 6, 0);

  frame3 = gtk_frame_new (_("Diff output"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox3), frame3, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame3), vbox4);

  diff_text = gtk_text_view_new ();
  gtk_widget_ref (diff_text);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "diff_text", diff_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (diff_text);
  gtk_box_pack_start (GTK_BOX (vbox4), diff_text, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (diff_text), 2);

  font_check = gtk_check_button_new_with_label (_("Fixed font"));
  gtk_widget_ref (font_check);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "font_check", font_check,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (font_check);
  gtk_box_pack_start (GTK_BOX (vbox4), font_check, FALSE, FALSE, 0);

  dialog_action_area1 = GNOME_DIALOG (diff_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (diff_dialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (diff_dialog), GNOME_STOCK_BUTTON_CLOSE);
  close_button = GTK_WIDGET (g_list_last (GNOME_DIALOG (diff_dialog)->buttons)->data);
  gtk_widget_ref (close_button);
  gtk_object_set_data_full (GTK_OBJECT (diff_dialog), "close_button", close_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close_button);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (diff_button), "clicked",
                      GTK_SIGNAL_FUNC (on_diff_dialog_diff),
                      plugin);
  gtk_signal_connect (GTK_OBJECT (font_check), "toggled",
                      GTK_SIGNAL_FUNC (on_font_toggled),
                      plugin);
  gtk_signal_connect (GTK_OBJECT (close_button), "clicked",
                      GTK_SIGNAL_FUNC (on_diff_dialog_close),
                      plugin);

  return diff_dialog;
}

GtkWidget*
create_about_dialog (void)
{
  const gchar *authors[] = {
    NULL
  };
  GtkWidget *about_dialog;

  about_dialog = gnome_about_new ("CVSLogViewer", VERSION,
                        _("Copyright: Marcus Bjurman 2003"),
								  NULL,
                        authors,
								  NULL, 
                        _("Small tool to browse CVS revisions of a single file."),
                        NULL);
  gtk_object_set_data (GTK_OBJECT (about_dialog), "about_dialog", about_dialog);
  gtk_window_set_modal (GTK_WINDOW (about_dialog), TRUE);

  return about_dialog;
}

